apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbpod
  labels:
    app: facebook
    env: lab
    version: fb-v1
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 3
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
        env: lab
    spec:
      containers:
        - name: fbcont
          image: nagaparameswarareddy/mydevops:tomcatserver
