apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting-app-pod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: voting-app-pod
    app: demo-voting-app
